// 아두이노로 전송하는 명령어 코드(index)와 사람이 읽을 수 있는 설명의 매핑 배열
// index 0 = 'SEND 0,5', index 1 = 'SEND 1,5', ... 순서 변경 금지
export const commandDescriptions = [
    '전원 OFF',
    '전원 ON 및 냉방. 약풍, 18도',
    '파워냉방',
    '냉방. 약풍, 18도',
    '냉방. 약풍, 19도',
    '냉방. 약풍, 20도',
    '냉방. 약풍, 21도',
    '냉방. 약풍, 22도',
    '냉방. 약풍, 23도',
    '냉방. 약풍, 24도',
    '냉방. 약풍, 25도',
    '냉방. 약풍, 26도',
    '냉방. 약풍, 27도',
    '냉방. 약풍, 28도',
    '냉방. 약풍, 29도',
    '냉방. 약풍, 30도',
    '냉방. 중풍, 18도',
    '냉방. 중풍, 19도',
    '냉방. 중풍, 20도',
    '냉방. 중풍, 21도',
    '냉방. 중풍, 22도',
    '냉방. 중풍, 23도',
    '냉방. 중풍, 24도',
    '냉방. 중풍, 25도',
    '냉방. 중풍, 26도',
    '냉방. 중풍, 27도',
    '냉방. 중풍, 28도',
    '냉방. 중풍, 29도',
    '냉방. 중풍, 30도',
    '냉방. 강풍, 18도',
    '냉방. 강풍, 19도',
    '냉방. 강풍, 20도',
    '냉방. 강풍, 21도',
    '냉방. 강풍, 22도',
    '냉방. 강풍, 23도',
    '냉방. 강풍, 24도',
    '냉방. 강풍, 25도',
    '냉방. 강풍, 26도',
    '냉방. 강풍, 27도',
    '냉방. 강풍, 28도',
    '냉방. 강풍, 29도',
    '냉방. 강풍, 30도',
    '냉방. 자동풍, 18도',
    '냉방. 자동풍, 19도',
    '냉방. 자동풍, 20도',
    '냉방. 자동풍, 21도',
    '냉방. 자동풍, 22도',
    '냉방. 자동풍, 23도',
    '냉방. 자동풍, 24도',
    '냉방. 자동풍, 25도',
    '냉방. 자동풍, 26도',
    '냉방. 자동풍, 27도',
    '냉방. 자동풍, 28도',
    '냉방. 자동풍, 29도',
    '냉방. 자동풍, 30도',
    '제습. 약풍, 18도',
    '제습. 약풍, 19도',
    '제습. 약풍, 20도',
    '제습. 약풍, 21도',
    '제습. 약풍, 22도',
    '제습. 약풍, 23도',
    '제습. 약풍, 24도',
    '제습. 약풍, 25도',
    '제습. 약풍, 26도',
    '제습. 약풍, 27도',
    '제습. 약풍, 28도',
    '제습. 약풍, 29도',
    '제습. 약풍, 30도',
    '제습. 중풍, 18도',
    '제습. 중풍, 19도',
    '제습. 중풍, 20도',
    '제습. 중풍, 21도',
    '제습. 중풍, 22도',
    '제습. 중풍, 23도',
    '제습. 중풍, 24도',
    '제습. 중풍, 25도',
    '제습. 중풍, 26도',
    '제습. 중풍, 27도',
    '제습. 중풍, 28도',
    '제습. 중풍, 29도',
    '제습. 중풍, 30도',
    '제습. 강풍, 18도',
    '제습. 강풍, 19도',
    '제습. 강풍, 20도',
    '제습. 강풍, 21도',
    '제습. 강풍, 22도',
    '제습. 강풍, 23도',
    '제습. 강풍, 24도',
    '제습. 강풍, 25도',
    '제습. 강풍, 26도',
    '제습. 강풍, 27도',
    '제습. 강풍, 28도',
    '제습. 강풍, 29도',
    '제습. 강풍, 30도',
    '제습. 자동풍, 18도',
    '제습. 자동풍, 19도',
    '제습. 자동풍, 20도',
    '제습. 자동풍, 21도',
    '제습. 자동풍, 22도',
    '제습. 자동풍, 23도',
    '제습. 자동풍, 24도',
    '제습. 자동풍, 25도',
    '제습. 자동풍, 26도',
    '제습. 자동풍, 27도',
    '제습. 자동풍, 28도',
    '제습. 자동풍, 29도',
    '제습. 자동풍, 30도',
];

const codes = [
    { type: 'power', code: '0' },
    { type: 'powerOn', code: '1' },
    { type: 'powerCooling', code: '2' },
    { type: 'cooling', wind: '약풍', temp: 18, code: '3' },
    { type: 'cooling', wind: '약풍', temp: 19, code: '4' },
    { type: 'cooling', wind: '약풍', temp: 20, code: '5' },
    { type: 'cooling', wind: '약풍', temp: 21, code: '6' },
    { type: 'cooling', wind: '약풍', temp: 22, code: '7' },
    { type: 'cooling', wind: '약풍', temp: 23, code: '8' },
    { type: 'cooling', wind: '약풍', temp: 24, code: '9' },
    { type: 'cooling', wind: '약풍', temp: 25, code: '10' },
    { type: 'cooling', wind: '약풍', temp: 26, code: '11' },
    { type: 'cooling', wind: '약풍', temp: 27, code: '12' },
    { type: 'cooling', wind: '약풍', temp: 28, code: '13' },
    { type: 'cooling', wind: '약풍', temp: 29, code: '14' },
    { type: 'cooling', wind: '약풍', temp: 30, code: '15' },
    { type: 'cooling', wind: '중풍', temp: 18, code: '16' },
    { type: 'cooling', wind: '중풍', temp: 19, code: '17' },
    { type: 'cooling', wind: '중풍', temp: 20, code: '18' },
    { type: 'cooling', wind: '중풍', temp: 21, code: '19' },
    { type: 'cooling', wind: '중풍', temp: 22, code: '20' },
    { type: 'cooling', wind: '중풍', temp: 23, code: '21' },
    { type: 'cooling', wind: '중풍', temp: 24, code: '22' },
    { type: 'cooling', wind: '중풍', temp: 25, code: '23' },
    { type: 'cooling', wind: '중풍', temp: 26, code: '24' },
    { type: 'cooling', wind: '중풍', temp: 27, code: '25' },
    { type: 'cooling', wind: '중풍', temp: 28, code: '26' },
    { type: 'cooling', wind: '중풍', temp: 29, code: '27' },
    { type: 'cooling', wind: '중풍', temp: 30, code: '28' },
    { type: 'cooling', wind: '강풍', temp: 18, code: '29' },
    { type: 'cooling', wind: '강풍', temp: 19, code: '30' },
    { type: 'cooling', wind: '강풍', temp: 20, code: '31' },
    { type: 'cooling', wind: '강풍', temp: 21, code: '32' },
    { type: 'cooling', wind: '강풍', temp: 22, code: '33' },
    { type: 'cooling', wind: '강풍', temp: 23, code: '34' },
    { type: 'cooling', wind: '강풍', temp: 24, code: '35' },
    { type: 'cooling', wind: '강풍', temp: 25, code: '36' },
    { type: 'cooling', wind: '강풍', temp: 26, code: '37' },
    { type: 'cooling', wind: '강풍', temp: 27, code: '38' },
    { type: 'cooling', wind: '강풍', temp: 28, code: '39' },
    { type: 'cooling', wind: '강풍', temp: 29, code: '40' },
    { type: 'cooling', wind: '강풍', temp: 30, code: '41' },
    { type: 'cooling', wind: '자동풍', temp: 18, code: '42' },
    { type: 'cooling', wind: '자동풍', temp: 19, code: '43' },
    { type: 'cooling', wind: '자동풍', temp: 20, code: '44' },
    { type: 'cooling', wind: '자동풍', temp: 21, code: '45' },
    { type: 'cooling', wind: '자동풍', temp: 22, code: '46' },
    { type: 'cooling', wind: '자동풍', temp: 23, code: '47' },
    { type: 'cooling', wind: '자동풍', temp: 24, code: '48' },
    { type: 'cooling', wind: '자동풍', temp: 25, code: '49' },
    { type: 'cooling', wind: '자동풍', temp: 26, code: '50' },
    { type: 'cooling', wind: '자동풍', temp: 27, code: '51' },
    { type: 'cooling', wind: '자동풍', temp: 28, code: '52' },
    { type: 'cooling', wind: '자동풍', temp: 29, code: '53' },
    { type: 'cooling', wind: '자동풍', temp: 30, code: '54' },
    { type: 'dehumidification', wind: '약풍', temp: 18, code: '55' },
    { type: 'dehumidification', wind: '약풍', temp: 19, code: '56' },
    { type: 'dehumidification', wind: '약풍', temp: 20, code: '57' },
    { type: 'dehumidification', wind: '약풍', temp: 21, code: '58' },
    { type: 'dehumidification', wind: '약풍', temp: 22, code: '59' },
    { type: 'dehumidification', wind: '약풍', temp: 23, code: '60' },
    { type: 'dehumidification', wind: '약풍', temp: 24, code: '61' },
    { type: 'dehumidification', wind: '약풍', temp: 25, code: '62' },
    { type: 'dehumidification', wind: '약풍', temp: 26, code: '63' },
    { type: 'dehumidification', wind: '약풍', temp: 27, code: '64' },
    { type: 'dehumidification', wind: '약풍', temp: 28, code: '65' },
    { type: 'dehumidification', wind: '약풍', temp: 29, code: '66' },
    { type: 'dehumidification', wind: '약풍', temp: 30, code: '67' },
    { type: 'dehumidification', wind: '중풍', temp: 18, code: '68' },
    { type: 'dehumidification', wind: '중풍', temp: 19, code: '69' },
    { type: 'dehumidification', wind: '중풍', temp: 20, code: '70' },
    { type: 'dehumidification', wind: '중풍', temp: 21, code: '71' },
    { type: 'dehumidification', wind: '중풍', temp: 22, code: '72' },
    { type: 'dehumidification', wind: '중풍', temp: 23, code: '73' },
    { type: 'dehumidification', wind: '중풍', temp: 24, code: '74' },
    { type: 'dehumidification', wind: '중풍', temp: 25, code: '75' },
    { type: 'dehumidification', wind: '중풍', temp: 26, code: '76' },
    { type: 'dehumidification', wind: '중풍', temp: 27, code: '77' },
    { type: 'dehumidification', wind: '중풍', temp: 28, code: '78' },
    { type: 'dehumidification', wind: '중풍', temp: 29, code: '79' },
    { type: 'dehumidification', wind: '중풍', temp: 30, code: '80' },
    { type: 'dehumidification', wind: '강풍', temp: 18, code: '81' },
    { type: 'dehumidification', wind: '강풍', temp: 19, code: '82' },
    { type: 'dehumidification', wind: '강풍', temp: 20, code: '83' },
    { type: 'dehumidification', wind: '강풍', temp: 21, code: '84' },
    { type: 'dehumidification', wind: '강풍', temp: 22, code: '85' },
    { type: 'dehumidification', wind: '강풍', temp: 23, code: '86' },
    { type: 'dehumidification', wind: '강풍', temp: 24, code: '87' },
    { type: 'dehumidification', wind: '강풍', temp: 25, code: '88' },
    { type: 'dehumidification', wind: '강풍', temp: 26, code: '89' },
    { type: 'dehumidification', wind: '강풍', temp: 27, code: '90' },
    { type: 'dehumidification', wind: '강풍', temp: 28, code: '91' },
    { type: 'dehumidification', wind: '강풍', temp: 29, code: '92' },
    { type: 'dehumidification', wind: '강풍', temp: 30, code: '93' },
    { type: 'dehumidification', wind: '자동풍', temp: 18, code: '94' },
    { type: 'dehumidification', wind: '자동풍', temp: 19, code: '95' },
    { type: 'dehumidification', wind: '자동풍', temp: 20, code: '96' },
    { type: 'dehumidification', wind: '자동풍', temp: 21, code: '97' },
    { type: 'dehumidification', wind: '자동풍', temp: 22, code: '98' },
    { type: 'dehumidification', wind: '자동풍', temp: 23, code: '99' },
    { type: 'dehumidification', wind: '자동풍', temp: 24, code: '100' },
    { type: 'dehumidification', wind: '자동풍', temp: 25, code: '101' },
    { type: 'dehumidification', wind: '자동풍', temp: 26, code: '102' },
    { type: 'dehumidification', wind: '자동풍', temp: 27, code: '103' },
    { type: 'dehumidification', wind: '자동풍', temp: 28, code: '104' },
    { type: 'dehumidification', wind: '자동풍', temp: 29, code: '105' },
    { type: 'dehumidification', wind: '자동풍', temp: 30, code: '106' },
];

// 'SEND N,5' 형식의 명령어에서 type/temp/wind 설정을 추출 (전원ON/OFF/파워냉방은 null 반환)
export const getCommandSettings = (command) => {
    const parts = command.split(' ');
    if (parts[0] !== 'SEND' || parts.length < 2) return null;
    const index = parseInt(parts[1].split(',')[0]);
    if (isNaN(index)) return null;
    const found = codes.find((c) => c.code === String(index));
    if (!found || !found.temp) return null;
    return { type: found.type, temp: found.temp, wind: found.wind };
};

// (type, temp, wind) 조합으로 아두이노 명령어 코드를 반환
export const getCommandIndex = (type, temp, wind) => {
    const found = codes.find((c) => c.type === type && c.temp === temp && c.wind === wind);
    return found ? found.code : null;
};

// 'SEND 3,5' 형식의 명령어를 사람이 읽을 수 있는 설명으로 변환
export const getCommandDescription = (command) => {
    const parts = command.split(' ');
    if (parts[0] === 'SEND' && parts.length > 1) {
        const index = parseInt(parts[1].split(',')[0]);
        if (!isNaN(index) && index >= 0 && index < commandDescriptions.length) {
            return commandDescriptions[index];
        }
    }
    return command; // 파싱 실패 시 원본 반환
};
